// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CanFrame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CanFrame GetRootAsCanFrame(ByteBuffer _bb) { return GetRootAsCanFrame(_bb, new CanFrame()); }
  public static CanFrame GetRootAsCanFrame(ByteBuffer _bb, CanFrame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyCanFrame(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, CanFrameVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CanFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint CanId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte CanData(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int CanDataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCanDataBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetCanDataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCanDataArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<Messages.CanFrame> CreateCanFrame(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      uint can_id = 0,
      VectorOffset can_dataOffset = default(VectorOffset)) {
    builder.StartTable(4);
    CanFrame.AddTimestamp(builder, timestamp);
    CanFrame.AddCanData(builder, can_dataOffset);
    CanFrame.AddCanId(builder, can_id);
    CanFrame.AddSequenceNumber(builder, sequence_number);
    return CanFrame.EndCanFrame(builder);
  }

  public static void StartCanFrame(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddCanId(FlatBufferBuilder builder, uint canId) { builder.AddUint(2, canId, 0); }
  public static void AddCanData(FlatBufferBuilder builder, VectorOffset canDataOffset) { builder.AddOffset(3, canDataOffset.Value, 0); }
  public static VectorOffset CreateCanDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateCanDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCanDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCanDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCanDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Messages.CanFrame> EndCanFrame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.CanFrame>(o);
  }
  public static void FinishCanFrameBuffer(FlatBufferBuilder builder, Offset<Messages.CanFrame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedCanFrameBuffer(FlatBufferBuilder builder, Offset<Messages.CanFrame> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class CanFrameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*CanId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*CanData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
