// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Location : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Location __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Latitude { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public double Longitude { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }

  public static Offset<Messages.Location> CreateLocation(FlatBufferBuilder builder, double Latitude, double Longitude) {
    builder.Prep(8, 16);
    builder.PutDouble(Longitude);
    builder.PutDouble(Latitude);
    return new Offset<Messages.Location>(builder.Offset);
  }
}


}
