// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Orientation : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Orientation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Pitch { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Roll { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Yaw { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

  public static Offset<Messages.Orientation> CreateOrientation(FlatBufferBuilder builder, float Pitch, float Roll, float Yaw) {
    builder.Prep(4, 12);
    builder.PutFloat(Yaw);
    builder.PutFloat(Roll);
    builder.PutFloat(Pitch);
    return new Offset<Messages.Orientation>(builder.Offset);
  }
}


}
