// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SimulatorMetadata : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SimulatorMetadata GetRootAsSimulatorMetadata(ByteBuffer _bb) { return GetRootAsSimulatorMetadata(_bb, new SimulatorMetadata()); }
  public static SimulatorMetadata GetRootAsSimulatorMetadata(ByteBuffer _bb, SimulatorMetadata obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifySimulatorMetadata(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, SimulatorMetadataVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SimulatorMetadata __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string MapId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMapIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMapIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMapIdArray() { return __p.__vector_as_array<byte>(8); }
  public double LatitudeLength { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public double LongitudeLength { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public Messages.Waypoint? Waypoints(int j) { int o = __p.__offset(14); return o != 0 ? (Messages.Waypoint?)(new Messages.Waypoint()).__assign(__p.__vector(o) + j * 24, __p.bb) : null; }
  public int WaypointsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Messages.SimulatorMetadata> CreateSimulatorMetadata(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      StringOffset map_idOffset = default(StringOffset),
      double latitude_length = 0.0,
      double longitude_length = 0.0,
      VectorOffset waypointsOffset = default(VectorOffset)) {
    builder.StartTable(6);
    SimulatorMetadata.AddLongitudeLength(builder, longitude_length);
    SimulatorMetadata.AddLatitudeLength(builder, latitude_length);
    SimulatorMetadata.AddTimestamp(builder, timestamp);
    SimulatorMetadata.AddWaypoints(builder, waypointsOffset);
    SimulatorMetadata.AddMapId(builder, map_idOffset);
    SimulatorMetadata.AddSequenceNumber(builder, sequence_number);
    return SimulatorMetadata.EndSimulatorMetadata(builder);
  }

  public static void StartSimulatorMetadata(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddMapId(FlatBufferBuilder builder, StringOffset mapIdOffset) { builder.AddOffset(2, mapIdOffset.Value, 0); }
  public static void AddLatitudeLength(FlatBufferBuilder builder, double latitudeLength) { builder.AddDouble(3, latitudeLength, 0.0); }
  public static void AddLongitudeLength(FlatBufferBuilder builder, double longitudeLength) { builder.AddDouble(4, longitudeLength, 0.0); }
  public static void AddWaypoints(FlatBufferBuilder builder, VectorOffset waypointsOffset) { builder.AddOffset(5, waypointsOffset.Value, 0); }
  public static void StartWaypointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(24, numElems, 8); }
  public static Offset<Messages.SimulatorMetadata> EndSimulatorMetadata(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.SimulatorMetadata>(o);
  }
  public static void FinishSimulatorMetadataBuffer(FlatBufferBuilder builder, Offset<Messages.SimulatorMetadata> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedSimulatorMetadataBuffer(FlatBufferBuilder builder, Offset<Messages.SimulatorMetadata> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class SimulatorMetadataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*MapId*/, false)
      && verifier.VerifyField(tablePos, 10 /*LatitudeLength*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*LongitudeLength*/, 8 /*double*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*Waypoints*/, 24 /*Messages.Waypoint*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
