// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VectornavReport : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static VectornavReport GetRootAsVectornavReport(ByteBuffer _bb) { return GetRootAsVectornavReport(_bb, new VectornavReport()); }
  public static VectornavReport GetRootAsVectornavReport(ByteBuffer _bb, VectornavReport obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyVectornavReport(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, VectornavReportVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VectornavReport __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public Messages.Location? Location { get { int o = __p.__offset(8); return o != 0 ? (Messages.Location?)(new Messages.Location()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Messages.Orientation? Orientation { get { int o = __p.__offset(10); return o != 0 ? (Messages.Orientation?)(new Messages.Orientation()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ushort NumSatellites { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public sbyte FixQuality { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }

  public static void StartVectornavReport(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddLocation(FlatBufferBuilder builder, Offset<Messages.Location> locationOffset) { builder.AddStruct(2, locationOffset.Value, 0); }
  public static void AddOrientation(FlatBufferBuilder builder, Offset<Messages.Orientation> orientationOffset) { builder.AddStruct(3, orientationOffset.Value, 0); }
  public static void AddNumSatellites(FlatBufferBuilder builder, ushort numSatellites) { builder.AddUshort(4, numSatellites, 0); }
  public static void AddFixQuality(FlatBufferBuilder builder, sbyte fixQuality) { builder.AddSbyte(5, fixQuality, 0); }
  public static Offset<Messages.VectornavReport> EndVectornavReport(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.VectornavReport>(o);
  }
  public static void FinishVectornavReportBuffer(FlatBufferBuilder builder, Offset<Messages.VectornavReport> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedVectornavReportBuffer(FlatBufferBuilder builder, Offset<Messages.VectornavReport> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class VectornavReportVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Location*/, 16 /*Messages.Location*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*Orientation*/, 12 /*Messages.Orientation*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*NumSatellites*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 14 /*FixQuality*/, 1 /*sbyte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
