// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Waypoint : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Waypoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Identifier { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public double Latitude { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }
  public double Longitude { get { return __p.bb.GetDouble(__p.bb_pos + 16); } }

  public static Offset<Messages.Waypoint> CreateWaypoint(FlatBufferBuilder builder, uint Identifier, double Latitude, double Longitude) {
    builder.Prep(8, 24);
    builder.PutDouble(Longitude);
    builder.PutDouble(Latitude);
    builder.Pad(4);
    builder.PutUint(Identifier);
    return new Offset<Messages.Waypoint>(builder.Offset);
  }
}


}
