// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ZedFrame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ZedFrame GetRootAsZedFrame(ByteBuffer _bb) { return GetRootAsZedFrame(_bb, new ZedFrame()); }
  public static ZedFrame GetRootAsZedFrame(ByteBuffer _bb, ZedFrame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyZedFrame(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ZedFrameVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ZedFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public int Width { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Height { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public byte Data(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<Messages.ZedFrame> CreateZedFrame(FlatBufferBuilder builder,
      ulong timestamp = 0,
      int width = 0,
      int height = 0,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(4);
    ZedFrame.AddTimestamp(builder, timestamp);
    ZedFrame.AddData(builder, dataOffset);
    ZedFrame.AddHeight(builder, height);
    ZedFrame.AddWidth(builder, width);
    return ZedFrame.EndZedFrame(builder);
  }

  public static void StartZedFrame(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddWidth(FlatBufferBuilder builder, int width) { builder.AddInt(1, width, 0); }
  public static void AddHeight(FlatBufferBuilder builder, int height) { builder.AddInt(2, height, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(3, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Messages.ZedFrame> EndZedFrame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.ZedFrame>(o);
  }
  public static void FinishZedFrameBuffer(FlatBufferBuilder builder, Offset<Messages.ZedFrame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedZedFrameBuffer(FlatBufferBuilder builder, Offset<Messages.ZedFrame> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ZedFrameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Width*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Height*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Data*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}