//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class GPSFeedbackMsg : Message
    {
        public const string k_RosMessageName = "igvc_messages/GPSFeedback";
        public override string RosMessageName => k_RosMessageName;

        public double latitude;
        public double longitude;

        public GPSFeedbackMsg()
        {
            this.latitude = 0.0;
            this.longitude = 0.0;
        }

        public GPSFeedbackMsg(double latitude, double longitude)
        {
            this.latitude = latitude;
            this.longitude = longitude;
        }

        public static GPSFeedbackMsg Deserialize(MessageDeserializer deserializer) => new GPSFeedbackMsg(deserializer);

        private GPSFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
        }

        public override string ToString()
        {
            return "GPSFeedbackMsg: " +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
