//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class IGVCSystemContextMsg : Message
    {
        public const string k_RosMessageName = "igvc_messages/IGVCSystemContext";
        public override string RosMessageName => k_RosMessageName;

        public int state;
        public bool mobility;
        public bool estop;

        public IGVCSystemContextMsg()
        {
            this.state = 0;
            this.mobility = false;
            this.estop = false;
        }

        public IGVCSystemContextMsg(int state, bool mobility, bool estop)
        {
            this.state = state;
            this.mobility = mobility;
            this.estop = estop;
        }

        public static IGVCSystemContextMsg Deserialize(MessageDeserializer deserializer) => new IGVCSystemContextMsg(deserializer);

        private IGVCSystemContextMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
            deserializer.Read(out this.mobility);
            deserializer.Read(out this.estop);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.mobility);
            serializer.Write(this.estop);
        }

        public override string ToString()
        {
            return "IGVCSystemContextMsg: " +
            "\nstate: " + state.ToString() +
            "\nmobility: " + mobility.ToString() +
            "\nestop: " + estop.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
