//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class IGVCDeviceStateMsg : Message
    {
        public const string k_RosMessageName = "igvc_messages/IGVCDeviceState";
        public override string RosMessageName => k_RosMessageName;

        public int state;
        public string device;

        public IGVCDeviceStateMsg()
        {
            this.state = 0;
            this.device = "";
        }

        public IGVCDeviceStateMsg(int state, string device)
        {
            this.state = state;
            this.device = device;
        }

        public static IGVCDeviceStateMsg Deserialize(MessageDeserializer deserializer) => new IGVCDeviceStateMsg(deserializer);

        private IGVCDeviceStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
            deserializer.Read(out this.device);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.device);
        }

        public override string ToString()
        {
            return "IGVCDeviceStateMsg: " +
            "\nstate: " + state.ToString() +
            "\ndevice: " + device.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
