//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class IGVCDeviceInitMsg : Message
    {
        public const string k_RosMessageName = "igvc_messages/IGVCDeviceInit";
        public override string RosMessageName => k_RosMessageName;

        public string target;
        public string json;

        public IGVCDeviceInitMsg()
        {
            this.target = "";
            this.json = "";
        }

        public IGVCDeviceInitMsg(string target, string json)
        {
            this.target = target;
            this.json = json;
        }

        public static IGVCDeviceInitMsg Deserialize(MessageDeserializer deserializer) => new IGVCDeviceInitMsg(deserializer);

        private IGVCDeviceInitMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target);
            deserializer.Read(out this.json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.json);
        }

        public override string ToString()
        {
            return "IGVCDeviceInitMsg: " +
            "\ntarget: " + target.ToString() +
            "\njson: " + json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
