//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class SafetyLightsMsg : Message
    {
        public const string k_RosMessageName = "igvc_messages/SafetyLights";
        public override string RosMessageName => k_RosMessageName;

        public short mode;
        public short blink_rate;
        public short red;
        public short green;
        public short blue;

        public SafetyLightsMsg()
        {
            this.mode = 0;
            this.blink_rate = 0;
            this.red = 0;
            this.green = 0;
            this.blue = 0;
        }

        public SafetyLightsMsg(short mode, short blink_rate, short red, short green, short blue)
        {
            this.mode = mode;
            this.blink_rate = blink_rate;
            this.red = red;
            this.green = green;
            this.blue = blue;
        }

        public static SafetyLightsMsg Deserialize(MessageDeserializer deserializer) => new SafetyLightsMsg(deserializer);

        private SafetyLightsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.blink_rate);
            deserializer.Read(out this.red);
            deserializer.Read(out this.green);
            deserializer.Read(out this.blue);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.blink_rate);
            serializer.Write(this.red);
            serializer.Write(this.green);
            serializer.Write(this.blue);
        }

        public override string ToString()
        {
            return "SafetyLightsMsg: " +
            "\nmode: " + mode.ToString() +
            "\nblink_rate: " + blink_rate.ToString() +
            "\nred: " + red.ToString() +
            "\ngreen: " + green.ToString() +
            "\nblue: " + blue.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
