// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SUS.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ImageFrame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ImageFrame GetRootAsImageFrame(ByteBuffer _bb) { return GetRootAsImageFrame(_bb, new ImageFrame()); }
  public static ImageFrame GetRootAsImageFrame(ByteBuffer _bb, ImageFrame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyImageFrame(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ImageFrameVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ImageFrame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Width { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Height { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Encoding { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEncodingBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetEncodingBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetEncodingArray() { return __p.__vector_as_array<byte>(12); }
  public string Identifier { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdentifierBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetIdentifierBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetIdentifierArray() { return __p.__vector_as_array<byte>(14); }
  public byte ImageData(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int ImageDataLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetImageDataBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetImageDataBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetImageDataArray() { return __p.__vector_as_array<byte>(16); }

  public static Offset<SUS.FlatBuffers.ImageFrame> CreateImageFrame(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      uint width = 0,
      uint height = 0,
      StringOffset encodingOffset = default(StringOffset),
      StringOffset identifierOffset = default(StringOffset),
      VectorOffset image_dataOffset = default(VectorOffset)) {
    builder.StartTable(7);
    ImageFrame.AddTimestamp(builder, timestamp);
    ImageFrame.AddImageData(builder, image_dataOffset);
    ImageFrame.AddIdentifier(builder, identifierOffset);
    ImageFrame.AddEncoding(builder, encodingOffset);
    ImageFrame.AddHeight(builder, height);
    ImageFrame.AddWidth(builder, width);
    ImageFrame.AddSequenceNumber(builder, sequence_number);
    return ImageFrame.EndImageFrame(builder);
  }

  public static void StartImageFrame(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddWidth(FlatBufferBuilder builder, uint width) { builder.AddUint(2, width, 0); }
  public static void AddHeight(FlatBufferBuilder builder, uint height) { builder.AddUint(3, height, 0); }
  public static void AddEncoding(FlatBufferBuilder builder, StringOffset encodingOffset) { builder.AddOffset(4, encodingOffset.Value, 0); }
  public static void AddIdentifier(FlatBufferBuilder builder, StringOffset identifierOffset) { builder.AddOffset(5, identifierOffset.Value, 0); }
  public static void AddImageData(FlatBufferBuilder builder, VectorOffset imageDataOffset) { builder.AddOffset(6, imageDataOffset.Value, 0); }
  public static VectorOffset CreateImageDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateImageDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateImageDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateImageDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartImageDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SUS.FlatBuffers.ImageFrame> EndImageFrame(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SUS.FlatBuffers.ImageFrame>(o);
  }
  public static void FinishImageFrameBuffer(FlatBufferBuilder builder, Offset<SUS.FlatBuffers.ImageFrame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedImageFrameBuffer(FlatBufferBuilder builder, Offset<SUS.FlatBuffers.ImageFrame> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ImageFrameVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Width*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Height*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 12 /*Encoding*/, false)
      && verifier.VerifyString(tablePos, 14 /*Identifier*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*ImageData*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
