/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Ekf_convergence : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "igvc_msgs/ekf_convergence";

        public Header header;
        public double data;

        public Ekf_convergence()
        {
            this.header = new Header();
            this.data = 0.0;
        }

        public Ekf_convergence(Header header, double data)
        {
            this.header = header;
            this.data = data;
        }
    }
}
