/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Ekf_state : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "igvc_msgs/ekf_state";

        public Header header;
        public double[] x_k;

        public Ekf_state()
        {
            this.header = new Header();
            this.x_k = new double[11];
        }

        public Ekf_state(Header header, double[] x_k)
        {
            this.header = header;
            this.x_k = x_k;
        }
    }
}
