/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class EKFConvergence : Message
    {
        public const string RosMessageName = "igvc_msgs/EKFConvergence";

        public Header header { get; set; }
        public double data { get; set; }

        public EKFConvergence()
        {
            this.header = new Header();
            this.data = 0.0;
        }

        public EKFConvergence(Header header, double data)
        {
            this.header = header;
            this.data = data;
        }
    }
}
