/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class EKFState : Message
    {
        public const string RosMessageName = "igvc_msgs/EKFState";

        public Header header { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public double global_heading { get; set; }
        public double x { get; set; }
        public double y { get; set; }
        public double yaw { get; set; }
        public double velocity { get; set; }
        public double yaw_rate { get; set; }
        public double left_angular_vel { get; set; }
        public double right_angular_vel { get; set; }
        public double acceleration { get; set; }

        public EKFState()
        {
            this.header = new Header();
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.global_heading = 0.0;
            this.x = 0.0;
            this.y = 0.0;
            this.yaw = 0.0;
            this.velocity = 0.0;
            this.yaw_rate = 0.0;
            this.left_angular_vel = 0.0;
            this.right_angular_vel = 0.0;
            this.acceleration = 0.0;
        }

        public EKFState(Header header, double latitude, double longitude, double global_heading, double x, double y, double yaw, double velocity, double yaw_rate, double left_angular_vel, double right_angular_vel, double acceleration)
        {
            this.header = header;
            this.latitude = latitude;
            this.longitude = longitude;
            this.global_heading = global_heading;
            this.x = x;
            this.y = y;
            this.yaw = yaw;
            this.velocity = velocity;
            this.yaw_rate = yaw_rate;
            this.left_angular_vel = left_angular_vel;
            this.right_angular_vel = right_angular_vel;
            this.acceleration = acceleration;
        }
    }
}
