/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Gps : Message
    {
        public const string RosMessageName = "igvc_msgs/gps";

        public double latitude { get; set; }
        public double longitude { get; set; }
        public bool hasSignal { get; set; }

        public Gps()
        {
            this.latitude = 0.0;
            this.longitude = 0.0;
            this.hasSignal = true;
        }

        public Gps(double latitude, double longitude, bool hasSignal)
        {
            this.latitude = latitude;
            this.longitude = longitude;
            this.hasSignal = hasSignal;
        }
    }
}
