/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Imuodom : Message
    {
        public const string RosMessageName = "igvc_msgs/imuodom";

        public float acceleration { get; set; }
        public float heading { get; set; }

        public Imuodom()
        {
            this.acceleration = 0.0f;
            this.heading = 0.0f;
        }

        public Imuodom(float acceleration, float heading)
        {
            this.acceleration = acceleration;
            this.heading = heading;
        }
    }
}
