/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Path : Message
    {
        public const string RosMessageName = "igvc_msgs/path";

        public Point[] points { get; set; }

        public Path()
        {
            this.points = new Point[0];
        }

        public Path(Point[] points)
        {
            this.points = points;
        }
    }
}
