/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Velocity : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "igvc_msgs/Velocity";

        public float leftVel;
        public float rightVel;

        public Velocity()
        {
            this.leftVel = 0.0f;
            this.rightVel = 0.0f;
        }

        public Velocity(float leftVel, float rightVel)
        {
            this.leftVel = leftVel;
            this.rightVel = rightVel;
        }
    }
}
