/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Igvc
{
    public class Velocity : Message
    {
        public const string RosMessageName = "igvc_msgs/velocity";

        public float leftVel { get; set; }
        public float rightVel { get; set; }

        public Velocity()
        {
            this.leftVel = 0.0f;
            this.rightVel = 0.0f;
        }

        public Velocity(float leftVel, float rightVel)
        {
            this.leftVel = leftVel;
            this.rightVel = rightVel;
        }
    }
}
