// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ArcCommand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ArcCommand GetRootAsArcCommand(ByteBuffer _bb) { return GetRootAsArcCommand(_bb, new ArcCommand()); }
  public static ArcCommand GetRootAsArcCommand(ByteBuffer _bb, ArcCommand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyArcCommand(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ArcCommandVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArcCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Purpose { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint CommandId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Data(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int DataLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<Messages.Arc.ArcCommand> CreateArcCommand(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      uint purpose = 0,
      uint command_id = 0,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(5);
    ArcCommand.AddTimestamp(builder, timestamp);
    ArcCommand.AddData(builder, dataOffset);
    ArcCommand.AddCommandId(builder, command_id);
    ArcCommand.AddPurpose(builder, purpose);
    ArcCommand.AddSequenceNumber(builder, sequence_number);
    return ArcCommand.EndArcCommand(builder);
  }

  public static void StartArcCommand(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddPurpose(FlatBufferBuilder builder, uint purpose) { builder.AddUint(2, purpose, 0); }
  public static void AddCommandId(FlatBufferBuilder builder, uint commandId) { builder.AddUint(3, commandId, 0); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(4, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<Messages.Arc.ArcCommand> EndArcCommand(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Arc.ArcCommand>(o);
  }
  public static void FinishArcCommandBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcCommand> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedArcCommandBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcCommand> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ArcCommandVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Purpose*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*CommandId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*Data*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
