// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ArcCapability : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ArcCapability GetRootAsArcCapability(ByteBuffer _bb) { return GetRootAsArcCapability(_bb, new ArcCapability()); }
  public static ArcCapability GetRootAsArcCapability(ByteBuffer _bb, ArcCapability obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyArcCapability(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ArcCapabilityVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArcCapability __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Purpose { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint VisionCapabilities { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint TelemetryCapabilities { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint MiscCapabilities { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<Messages.Arc.ArcCapability> CreateArcCapability(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      uint purpose = 0,
      uint vision_capabilities = 0,
      uint telemetry_capabilities = 0,
      uint misc_capabilities = 0) {
    builder.StartTable(6);
    ArcCapability.AddTimestamp(builder, timestamp);
    ArcCapability.AddMiscCapabilities(builder, misc_capabilities);
    ArcCapability.AddTelemetryCapabilities(builder, telemetry_capabilities);
    ArcCapability.AddVisionCapabilities(builder, vision_capabilities);
    ArcCapability.AddPurpose(builder, purpose);
    ArcCapability.AddSequenceNumber(builder, sequence_number);
    return ArcCapability.EndArcCapability(builder);
  }

  public static void StartArcCapability(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddPurpose(FlatBufferBuilder builder, uint purpose) { builder.AddUint(2, purpose, 0); }
  public static void AddVisionCapabilities(FlatBufferBuilder builder, uint visionCapabilities) { builder.AddUint(3, visionCapabilities, 0); }
  public static void AddTelemetryCapabilities(FlatBufferBuilder builder, uint telemetryCapabilities) { builder.AddUint(4, telemetryCapabilities, 0); }
  public static void AddMiscCapabilities(FlatBufferBuilder builder, uint miscCapabilities) { builder.AddUint(5, miscCapabilities, 0); }
  public static Offset<Messages.Arc.ArcCapability> EndArcCapability(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Arc.ArcCapability>(o);
  }
  public static void FinishArcCapabilityBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcCapability> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedArcCapabilityBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcCapability> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ArcCapabilityVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Purpose*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*VisionCapabilities*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*TelemetryCapabilities*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*MiscCapabilities*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
