// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

public enum ArcCommandId : sbyte
{
  UnknownCommand = 0,
  ToolsStartOpenCvCalibration = 1,
  ToolsStopOpenCvCalibration = 2,
  ToolsSaveOpenCvCalibration = 3,
  ToolsStartHsvCalibration = 4,
  ToolsStopHsvCalibration = 5,
  ToolsEditHsvCalibration = 6,
  ToolsSaveHsvCalibration = 7,
};


}
