// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

public enum ArcCommandPurpose : sbyte
{
  UnknownPurpose = 0,
  Request = 1,
  Response = 2,
};


}
