// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ArcHistogram : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ArcHistogram GetRootAsArcHistogram(ByteBuffer _bb) { return GetRootAsArcHistogram(_bb, new ArcHistogram()); }
  public static ArcHistogram GetRootAsArcHistogram(ByteBuffer _bb, ArcHistogram obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyArcHistogram(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ArcHistogramVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArcHistogram __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public float MinHue { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MaxHue { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MinSaturation { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MaxSaturation { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MinValue { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MaxValue { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Messages.Arc.ArcHistogram> CreateArcHistogram(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      float min_hue = 0.0f,
      float max_hue = 0.0f,
      float min_saturation = 0.0f,
      float max_saturation = 0.0f,
      float min_value = 0.0f,
      float max_value = 0.0f) {
    builder.StartTable(8);
    ArcHistogram.AddTimestamp(builder, timestamp);
    ArcHistogram.AddMaxValue(builder, max_value);
    ArcHistogram.AddMinValue(builder, min_value);
    ArcHistogram.AddMaxSaturation(builder, max_saturation);
    ArcHistogram.AddMinSaturation(builder, min_saturation);
    ArcHistogram.AddMaxHue(builder, max_hue);
    ArcHistogram.AddMinHue(builder, min_hue);
    ArcHistogram.AddSequenceNumber(builder, sequence_number);
    return ArcHistogram.EndArcHistogram(builder);
  }

  public static void StartArcHistogram(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddMinHue(FlatBufferBuilder builder, float minHue) { builder.AddFloat(2, minHue, 0.0f); }
  public static void AddMaxHue(FlatBufferBuilder builder, float maxHue) { builder.AddFloat(3, maxHue, 0.0f); }
  public static void AddMinSaturation(FlatBufferBuilder builder, float minSaturation) { builder.AddFloat(4, minSaturation, 0.0f); }
  public static void AddMaxSaturation(FlatBufferBuilder builder, float maxSaturation) { builder.AddFloat(5, maxSaturation, 0.0f); }
  public static void AddMinValue(FlatBufferBuilder builder, float minValue) { builder.AddFloat(6, minValue, 0.0f); }
  public static void AddMaxValue(FlatBufferBuilder builder, float maxValue) { builder.AddFloat(7, maxValue, 0.0f); }
  public static Offset<Messages.Arc.ArcHistogram> EndArcHistogram(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Arc.ArcHistogram>(o);
  }
  public static void FinishArcHistogramBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcHistogram> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedArcHistogramBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcHistogram> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ArcHistogramVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*MinHue*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*MaxHue*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*MinSaturation*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*MaxSaturation*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*MinValue*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*MaxValue*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
