// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Arc
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ArcLog : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ArcLog GetRootAsArcLog(ByteBuffer _bb) { return GetRootAsArcLog(_bb, new ArcLog()); }
  public static ArcLog GetRootAsArcLog(ByteBuffer _bb, ArcLog obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyArcLog(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ArcLogVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ArcLog __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint SequenceNumber { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string MethodCaller { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMethodCallerBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetMethodCallerBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetMethodCallerArray() { return __p.__vector_as_array<byte>(8); }
  public string LogLevel { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLogLevelBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetLogLevelBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetLogLevelArray() { return __p.__vector_as_array<byte>(10); }
  public string Message { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<Messages.Arc.ArcLog> CreateArcLog(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint sequence_number = 0,
      StringOffset method_callerOffset = default(StringOffset),
      StringOffset log_levelOffset = default(StringOffset),
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(5);
    ArcLog.AddTimestamp(builder, timestamp);
    ArcLog.AddMessage(builder, messageOffset);
    ArcLog.AddLogLevel(builder, log_levelOffset);
    ArcLog.AddMethodCaller(builder, method_callerOffset);
    ArcLog.AddSequenceNumber(builder, sequence_number);
    return ArcLog.EndArcLog(builder);
  }

  public static void StartArcLog(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddSequenceNumber(FlatBufferBuilder builder, uint sequenceNumber) { builder.AddUint(1, sequenceNumber, 0); }
  public static void AddMethodCaller(FlatBufferBuilder builder, StringOffset methodCallerOffset) { builder.AddOffset(2, methodCallerOffset.Value, 0); }
  public static void AddLogLevel(FlatBufferBuilder builder, StringOffset logLevelOffset) { builder.AddOffset(3, logLevelOffset.Value, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(4, messageOffset.Value, 0); }
  public static Offset<Messages.Arc.ArcLog> EndArcLog(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Arc.ArcLog>(o);
  }
  public static void FinishArcLogBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcLog> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedArcLogBuffer(FlatBufferBuilder builder, Offset<Messages.Arc.ArcLog> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ArcLogVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*SequenceNumber*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*MethodCaller*/, false)
      && verifier.VerifyString(tablePos, 10 /*LogLevel*/, false)
      && verifier.VerifyString(tablePos, 12 /*Message*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
