//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class UpdateDeviceStateResponse : Message
    {
        public const string k_RosMessageName = "igvc_messages/UpdateDeviceState";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public UpdateDeviceStateResponse()
        {
            this.ok = false;
        }

        public UpdateDeviceStateResponse(bool ok)
        {
            this.ok = ok;
        }

        public static UpdateDeviceStateResponse Deserialize(MessageDeserializer deserializer) => new UpdateDeviceStateResponse(deserializer);

        private UpdateDeviceStateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "UpdateDeviceStateResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
