//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class UpdateConfigurationRequest : Message
    {
        public const string k_RosMessageName = "igvc_messages/UpdateConfiguration";
        public override string RosMessageName => k_RosMessageName;

        public string json;

        public UpdateConfigurationRequest()
        {
            this.json = "";
        }

        public UpdateConfigurationRequest(string json)
        {
            this.json = json;
        }

        public static UpdateConfigurationRequest Deserialize(MessageDeserializer deserializer) => new UpdateConfigurationRequest(deserializer);

        private UpdateConfigurationRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.json);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.json);
        }

        public override string ToString()
        {
            return "UpdateConfigurationRequest: " +
            "\njson: " + json.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
