//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class UpdateConfigurationResponse : Message
    {
        public const string k_RosMessageName = "igvc_messages/UpdateConfiguration";
        public override string RosMessageName => k_RosMessageName;

        public bool ok;

        public UpdateConfigurationResponse()
        {
            this.ok = false;
        }

        public UpdateConfigurationResponse(bool ok)
        {
            this.ok = ok;
        }

        public static UpdateConfigurationResponse Deserialize(MessageDeserializer deserializer) => new UpdateConfigurationResponse(deserializer);

        private UpdateConfigurationResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ok);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ok);
        }

        public override string ToString()
        {
            return "UpdateConfigurationResponse: " +
            "\nok: " + ok.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
