//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IgvcMessages
{
    [Serializable]
    public class UpdateDeviceStateRequest : Message
    {
        public const string k_RosMessageName = "igvc_messages/UpdateDeviceState";
        public override string RosMessageName => k_RosMessageName;

        public string device;
        public int state;

        public UpdateDeviceStateRequest()
        {
            this.device = "";
            this.state = 0;
        }

        public UpdateDeviceStateRequest(string device, int state)
        {
            this.device = device;
            this.state = state;
        }

        public static UpdateDeviceStateRequest Deserialize(MessageDeserializer deserializer) => new UpdateDeviceStateRequest(deserializer);

        private UpdateDeviceStateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.device);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.device);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "UpdateDeviceStateRequest: " +
            "\ndevice: " + device.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
