// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Performance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MetricDefinition : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MetricDefinition GetRootAsMetricDefinition(ByteBuffer _bb) { return GetRootAsMetricDefinition(_bb, new MetricDefinition()); }
  public static MetricDefinition GetRootAsMetricDefinition(ByteBuffer _bb, MetricDefinition obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MetricDefinition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Subsystem { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubsystemBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSubsystemBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSubsystemArray() { return __p.__vector_as_array<byte>(4); }
  public string Group { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGroupBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetGroupBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetGroupArray() { return __p.__vector_as_array<byte>(6); }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
  public string Unit { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnitBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetUnitBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetUnitArray() { return __p.__vector_as_array<byte>(10); }
<<<<<<< HEAD
  public Messages.Performance.MetricAggregate Aggregate { get { int o = __p.__offset(12); return o != 0 ? (Messages.Performance.MetricAggregate)__p.bb.GetSbyte(o + __p.bb_pos) : Messages.Performance.MetricAggregate.Last; } }

  public static Offset<Messages.Performance.MetricDefinition> CreateMetricDefinition(FlatBufferBuilder builder,
=======
  public Messages.performance.MetricAggregate Aggregate { get { int o = __p.__offset(12); return o != 0 ? (Messages.performance.MetricAggregate)__p.bb.GetSbyte(o + __p.bb_pos) : Messages.performance.MetricAggregate.Last; } }

  public static Offset<Messages.performance.MetricDefinition> CreateMetricDefinition(FlatBufferBuilder builder,
>>>>>>> be59f75216ab0c9450a468f0bd6a41cbb127ace8
      StringOffset subsystemOffset = default(StringOffset),
      StringOffset groupOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      StringOffset unitOffset = default(StringOffset),
<<<<<<< HEAD
      Messages.Performance.MetricAggregate aggregate = Messages.Performance.MetricAggregate.Last) {
=======
      Messages.performance.MetricAggregate aggregate = Messages.performance.MetricAggregate.Last) {
>>>>>>> be59f75216ab0c9450a468f0bd6a41cbb127ace8
    builder.StartTable(5);
    MetricDefinition.AddUnit(builder, unitOffset);
    MetricDefinition.AddName(builder, nameOffset);
    MetricDefinition.AddGroup(builder, groupOffset);
    MetricDefinition.AddSubsystem(builder, subsystemOffset);
    MetricDefinition.AddAggregate(builder, aggregate);
    return MetricDefinition.EndMetricDefinition(builder);
  }

  public static void StartMetricDefinition(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddSubsystem(FlatBufferBuilder builder, StringOffset subsystemOffset) { builder.AddOffset(0, subsystemOffset.Value, 0); }
  public static void AddGroup(FlatBufferBuilder builder, StringOffset groupOffset) { builder.AddOffset(1, groupOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddUnit(FlatBufferBuilder builder, StringOffset unitOffset) { builder.AddOffset(3, unitOffset.Value, 0); }
<<<<<<< HEAD
  public static void AddAggregate(FlatBufferBuilder builder, Messages.Performance.MetricAggregate aggregate) { builder.AddSbyte(4, (sbyte)aggregate, 0); }
  public static Offset<Messages.Performance.MetricDefinition> EndMetricDefinition(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.Performance.MetricDefinition>(o);
=======
  public static void AddAggregate(FlatBufferBuilder builder, Messages.performance.MetricAggregate aggregate) { builder.AddSbyte(4, (sbyte)aggregate, 0); }
  public static Offset<Messages.performance.MetricDefinition> EndMetricDefinition(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.performance.MetricDefinition>(o);
>>>>>>> be59f75216ab0c9450a468f0bd6a41cbb127ace8
  }
}


static public class MetricDefinitionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Subsystem*/, false)
      && verifier.VerifyString(tablePos, 6 /*Group*/, false)
      && verifier.VerifyString(tablePos, 8 /*Name*/, false)
      && verifier.VerifyString(tablePos, 10 /*Unit*/, false)
<<<<<<< HEAD
      && verifier.VerifyField(tablePos, 12 /*Aggregate*/, 1 /*Messages.Performance.MetricAggregate*/, 1, false)
=======
      && verifier.VerifyField(tablePos, 12 /*Aggregate*/, 1 /*Messages.performance.MetricAggregate*/, 1, false)
>>>>>>> be59f75216ab0c9450a468f0bd6a41cbb127ace8
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
