// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Performance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MetricSample : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MetricSample GetRootAsMetricSample(ByteBuffer _bb) { return GetRootAsMetricSample(_bb, new MetricSample()); }
  public static MetricSample GetRootAsMetricSample(ByteBuffer _bb, MetricSample obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMetricSample(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MetricSampleVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MetricSample __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Subsystem { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSubsystemBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetSubsystemBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetSubsystemArray() { return __p.__vector_as_array<byte>(4); }
  public string Group { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGroupBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetGroupBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetGroupArray() { return __p.__vector_as_array<byte>(6); }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(8); }
  public string Unit { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnitBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetUnitBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetUnitArray() { return __p.__vector_as_array<byte>(10); }
  public Messages.performance.MetricAggregate Aggregate { get { int o = __p.__offset(12); return o != 0 ? (Messages.performance.MetricAggregate)__p.bb.GetSbyte(o + __p.bb_pos) : Messages.performance.MetricAggregate.Last; } }
  public ulong TimestampUnixMs { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public double Value { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<Messages.performance.MetricSample> CreateMetricSample(FlatBufferBuilder builder,
      StringOffset subsystemOffset = default(StringOffset),
      StringOffset groupOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      StringOffset unitOffset = default(StringOffset),
      Messages.performance.MetricAggregate aggregate = Messages.performance.MetricAggregate.Last,
      ulong timestamp_unix_ms = 0,
      double value = 0.0) {
    builder.StartTable(7);
    MetricSample.AddValue(builder, value);
    MetricSample.AddTimestampUnixMs(builder, timestamp_unix_ms);
    MetricSample.AddUnit(builder, unitOffset);
    MetricSample.AddName(builder, nameOffset);
    MetricSample.AddGroup(builder, groupOffset);
    MetricSample.AddSubsystem(builder, subsystemOffset);
    MetricSample.AddAggregate(builder, aggregate);
    return MetricSample.EndMetricSample(builder);
  }

  public static void StartMetricSample(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddSubsystem(FlatBufferBuilder builder, StringOffset subsystemOffset) { builder.AddOffset(0, subsystemOffset.Value, 0); }
  public static void AddGroup(FlatBufferBuilder builder, StringOffset groupOffset) { builder.AddOffset(1, groupOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddUnit(FlatBufferBuilder builder, StringOffset unitOffset) { builder.AddOffset(3, unitOffset.Value, 0); }
  public static void AddAggregate(FlatBufferBuilder builder, Messages.performance.MetricAggregate aggregate) { builder.AddSbyte(4, (sbyte)aggregate, 0); }
  public static void AddTimestampUnixMs(FlatBufferBuilder builder, ulong timestampUnixMs) { builder.AddUlong(5, timestampUnixMs, 0); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(6, value, 0.0); }
  public static Offset<Messages.performance.MetricSample> EndMetricSample(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.performance.MetricSample>(o);
  }
  public static void FinishMetricSampleBuffer(FlatBufferBuilder builder, Offset<Messages.performance.MetricSample> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMetricSampleBuffer(FlatBufferBuilder builder, Offset<Messages.performance.MetricSample> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MetricSampleVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Subsystem*/, false)
      && verifier.VerifyString(tablePos, 6 /*Group*/, false)
      && verifier.VerifyString(tablePos, 8 /*Name*/, false)
      && verifier.VerifyString(tablePos, 10 /*Unit*/, false)
      && verifier.VerifyField(tablePos, 12 /*Aggregate*/, 1 /*Messages.performance.MetricAggregate*/, 1, false)
      && verifier.VerifyField(tablePos, 14 /*TimestampUnixMs*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 16 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
