// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Performance
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MetricSchema : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MetricSchema GetRootAsMetricSchema(ByteBuffer _bb) { return GetRootAsMetricSchema(_bb, new MetricSchema()); }
  public static MetricSchema GetRootAsMetricSchema(ByteBuffer _bb, MetricSchema obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMetricSchema(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MetricSchemaVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MetricSchema __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Messages.performance.MetricDefinition? Metrics(int j) { int o = __p.__offset(4); return o != 0 ? (Messages.performance.MetricDefinition?)(new Messages.performance.MetricDefinition()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MetricsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Messages.performance.MetricSchema> CreateMetricSchema(FlatBufferBuilder builder,
      VectorOffset metricsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    MetricSchema.AddMetrics(builder, metricsOffset);
    return MetricSchema.EndMetricSchema(builder);
  }

  public static void StartMetricSchema(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMetrics(FlatBufferBuilder builder, VectorOffset metricsOffset) { builder.AddOffset(0, metricsOffset.Value, 0); }
  public static VectorOffset CreateMetricsVector(FlatBufferBuilder builder, Offset<Messages.performance.MetricDefinition>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMetricsVectorBlock(FlatBufferBuilder builder, Offset<Messages.performance.MetricDefinition>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMetricsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Messages.performance.MetricDefinition>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMetricsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Messages.performance.MetricDefinition>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMetricsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Messages.performance.MetricSchema> EndMetricSchema(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Messages.performance.MetricSchema>(o);
  }
  public static void FinishMetricSchemaBuffer(FlatBufferBuilder builder, Offset<Messages.performance.MetricSchema> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMetricSchemaBuffer(FlatBufferBuilder builder, Offset<Messages.performance.MetricSchema> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MetricSchemaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Metrics*/, Messages.performance.MetricDefinitionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
