// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Messages.Performance
{

public enum MetricAggregate : sbyte
{
  Last = 0,
  Average = 1,
  Min = 2,
  Max = 3,
};


}
