
/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Nrc
{
    public class DriveCommand : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nrc_msgs/DriveCommand";

        public float heading;
        public float speed;

        public DriveCommand()
        {
            this.heading = 0.0f;
            this.speed = 0.0f;
        }

        public DriveCommand(float heading, float speed)
        {
            this.heading = heading;
            this.speed = speed;
        }
    }
}
