/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Nrc
{
    public class DriveStatus : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "nrc_msgs/DriveStatus";

        public sbyte device_id;
        public float right_speed;
        public float left_speed;
        public float acceleration;
        public float yaw;

        public DriveStatus()
        {
            this.device_id = 0;
            this.right_speed = 0.0f;
            this.left_speed = 0.0f;
            this.acceleration = 0.0f;
            this.yaw = 0.0f;
        }

        public DriveStatus(sbyte device_id, float right_speed, float left_speed, float acceleration, float yaw)
        {
            this.device_id = device_id;
            this.right_speed = right_speed;
            this.left_speed = left_speed;
            this.acceleration = acceleration;
            this.yaw = yaw;
        }
    }
}
