/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Autonav
{
    public class MotorInput : Message
    {
        public const string RosMessageName = "autonav_msgs/MotorInput";

        //  left_motor - float32 - The speed of the left motor
        public float left_motor { get; set; }
        //  right_motor - float32 - The speed of the right motor
        public float right_motor { get; set; }

        public MotorInput()
        {
            this.left_motor = 0.0f;
            this.right_motor = 0.0f;
        }

        public MotorInput(float left_motor, float right_motor)
        {
            this.left_motor = left_motor;
            this.right_motor = right_motor;
        }
    }
}
